### ISSUE TITLE
Error in java solution

### ISSUE THREAD

**Issue by mukitul** [shubhamthrills/LeetCode-Challenge-May#1]
'i' points to bit position.
So it should be incremented at each iteration not inside if condition block.

Link: https://github.com/shubhamthrills/LeetCode-Challenge/blob/master/May%20DAY%2004.pdf

**Comment by shubhamthrills** [comment]
Yes, you are correct.
It's my fault there


class Solution {
    public int findComplement(int num) {
        int i = 0, res = 0;
        while(num>0){
            if((1 & num) == 0) res += Math.pow(2, i);
            num = num >> 1;
            i=i+1;
        }
        return res;
    }
}

**Comment by shubhamthrills** [comment]
> 'i' points to bit position.
> So it should be incremented at each iteration not inside if condition block.
> 
> Link: https://github.com/shubhamthrills/LeetCode-Challenge/blob/master/May%20DAY%2004.pdf

Yes,
It's my fault there

class Solution {
public int findComplement(int num) {
int i = 0, res = 0;
while(num>0){
if((1 & num) == 0) res += Math.pow(2, i);
num = num >> 1;
i=i+1;
}
return res;
}
}

**Comment by shubhamthrills** [comment]
JAVA Solution Updated Solution:


Yes, you are correct.
It's my fault there

class Solution {
public int findComplement(int num) {
int i = 0, res = 0;
while(num>0){
if((1 & num) == 0) res += Math.pow(2, i);
num = num >> 1;
i=i+1;
}
return res;
}
}
